<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Personnage
 */
require_once('Personnage.class.php');

class Guerrier extends Personnage {


	/**
	 * @access public
	 * @return void
	 */

	public final  function gagnerExperience() {

	}


	/**
	 * @access public
	 * @param int $force 
	 * @return int
	 */

	public final  function recevoirDegats($force) {

	}


}
?>