<?php
/**
 * mes commentaires
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Personnage {

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $atout;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $degats;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $experience;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $force_perso;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $niveau;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $nom;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $nombre_coups;


	/**
	 * @access public
	 * @param array $donnees 
	 * @return void
	 */

	public final  function __construct($donnees) {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function estEndormi() {

	}


}
?>